name: Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository with Emscripten tool
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # need this to get versioning correct
        repository: 'StoneOrbits/VortexEngine'
        path: 'VortexEngine'
        ref: 'desktop'

    # Build Vortex cli tool
    - name: Build Vortex CLI Tool
      run: |
        cd VortexEngine/VortexEngine/VortexCLI
        # fetch tags first to ensure versioning is correct
        make -j

    # Install Emscripten dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 nodejs cmake

    # Install Emscripten
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install b363a836e75a245c548b7a6a021822d8c9e4c6df
        ./emsdk activate b363a836e75a245c548b7a6a021822d8c9e4c6df
        source ./emsdk_env.sh

    # Build using Emscripten
    - name: Build WebAssembly with Emscripten
      run: |
        source emsdk/emsdk_env.sh
        cd VortexEngine/VortexEngine/VortexLib
        make clean
        make -j wasm

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Add Linode to known_hosts
      run: ssh-keyscan 198.74.48.18 >> ~/.ssh/known_hosts
    
    - name: Deploy to Linode
      run: |
        scp VortexEngine/VortexEngine/VortexLib/VortexLib.js vortex@198.74.48.18:~/VortexCommunity/public/js/VortexLib.js
        scp VortexEngine/VortexEngine/VortexLib/VortexLib.wasm vortex@198.74.48.18:~/VortexCommunity/public/js/VortexLib.wasm
        scp VortexEngine/VortexEngine/VortexCLI/vortex vortex@198.74.48.18:~/vortex
        ssh vortex@198.74.48.18 'sudo /usr/bin/mv /home/vortex/vortex /usr/local/bin/vortex'
        ssh vortex@198.74.48.18 'sudo systemctl stop vortex-community'
        ssh vortex@198.74.48.18 'cd /home/vortex/VortexCommunity && git pull && chmod +x start.sh'
        ssh vortex@198.74.48.18 'sudo systemctl start vortex-community'
    
