name: Deploy to Linode

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build
      run: npm install

    - name: Setup SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
    - name: Add Linode to known_hosts
      run: ssh-keyscan 198.74.48.18 >> ~/.ssh/known_hosts
    
    - name: Deploy to Linode
      run: |
        ssh vortex@198.74.48.18 'sudo apt-get update && sudo apt-get install -y nodejs npm mongodb'
        ssh vortex@198.74.48.18 'sudo systemctl start mongod'
        scp -r . vortex@198.74.48.18:/home/vortex/
        ssh vortex@198.74.48.18 'cd /home/vortex/ && npm install && npm start'
    
